general.import = [
#	"~/.config/alacritty/themes/themes/monokai.toml"
	# "~/.config/alacritty/themes/themes/cyber_dat.toml"
#	"~/.config/alacritty/themes/themes/everforest_dark2.toml"
"~/.config/alacritty/themes/themes/tokyo_night_enhanced.toml"
]

[env]
TERM = "xterm-256color"

[window]
title = "Terminal"
opacity = 0.85
blur = true

[font]
size = 12.0

[font.bold]
family = "Hurmit Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hurmit Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hurmit Nerd Font"
style = "Italic"

[font.normal]
family = "Hurmit Nerd Font"
style = "Regular"

